apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dep.yml
  - svc.yml

commonLabels:
  app.kubernetes.io/name: project-test
  app.kubernetes.io/component: project-test
  app.kubernetes.io/part-of: amine-projects